[package]
name = "waybar-upower"
version = "0.1.0"
authors = ["Hilmar Gústafsson <hilmargustafs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
upower_dbus = "0.1.0"
serde = { version = "1.0.56", features = ["derive"] }
serde_json = "1.0.56"
